/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package VIEW;

import java.awt.Dimension;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDateTime;

import CTR.RelatorioCTR;
import CTR.FuncionarioCTR;

/**
 *
 * @author Heitor
 */
public class RelatorioVIEW extends javax.swing.JInternalFrame {

    RelatorioCTR relatorioCTR = new RelatorioCTR();
    FuncionarioCTR funcionarioCTR = new FuncionarioCTR();

    SimpleDateFormat date = new SimpleDateFormat("dd/MM/yyyy");
    ResultSet rs;

    DefaultTableModel modelo_jtl_clienteFuncionario;
    DefaultTableModel modelo_jtl_clienteData;

    /**
     * Creates new form RelatorioVIEW
     */
    public RelatorioVIEW() {
        initComponents();
        modelo_jtl_clienteFuncionario = (DefaultTableModel) this.jtl_clientesFuncionario.getModel();
        modelo_jtl_clienteData = (DefaultTableModel) this.jtl_clientesDate.getModel();
    }

    public void setPosition() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnGerar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        numeroTotalClientes = new javax.swing.JTextField();
        numeroTotalFuncionarios = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtl_clientesDate = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtl_clientesFuncionario = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Relatórios");

        btnGerar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnGerar.setText("Gerar");
        btnGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Número Total de Clientes:");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Clientes por Funcionário");

        btnSair.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        numeroTotalClientes.setEditable(false);
        numeroTotalClientes.setForeground(new java.awt.Color(204, 204, 204));

        numeroTotalFuncionarios.setEditable(false);
        numeroTotalFuncionarios.setForeground(new java.awt.Color(204, 204, 204));

        jtl_clientesDate.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Qtd. Clientes"
            }
        ));
        jScrollPane1.setViewportView(jtl_clientesDate);

        jtl_clientesFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Funcionário", "Qtd. Clientes"
            }
        ));
        jScrollPane2.setViewportView(jtl_clientesFuncionario);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Número Total de Funcionários:");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("Clientes por Mês e Ano");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numeroTotalFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numeroTotalClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(48, 48, 48))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGerar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(173, 173, 173))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroTotalClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroTotalFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGerar)
                    .addComponent(btnSair))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarActionPerformed
        this.numeroTotalClientes.setText(String.valueOf(this.relatorioCTR.retornarNumeroClienteTotais()));
        this.numeroTotalFuncionarios.setText(String.valueOf(this.relatorioCTR.retornarNumeroFuncionarioTotais()));
        this.getNumeroDeClientePorData();
        this.getNumeroDeClientesPorFuncionario();
    }//GEN-LAST:event_btnGerarActionPerformed

    private void getNumeroDeClientesPorFuncionario() {
        try {
            this.modelo_jtl_clienteFuncionario.setRowCount(0);
            rs = funcionarioCTR.consultar(null, 3);
            while (rs.next()) {
                String nomeFuncionario = rs.getString("nome");
                int numeroClienteFuncionario = relatorioCTR.retornarNumeroDeClientesPorFuncionario(
                        Integer.parseInt(rs.getString("id_funcionario")));
                this.modelo_jtl_clienteFuncionario.addRow(new Object[]{
                    nomeFuncionario,
                    numeroClienteFuncionario
                });
            }
        } catch (Exception err) {
            System.out.println("RelatorioVIEW.getNumeroDeClientesPorFuncionario: " + err.getMessage());
            JOptionPane.showMessageDialog(null, "Não foi retornar dados");
        }

    }

    private void getNumeroDeClientePorData() {
        this.modelo_jtl_clienteData.setNumRows(0);
        
        int mesAtual = LocalDateTime.now().getMonthValue();
        int anoAtual = LocalDateTime.now().getYear();

        for (int i = 0; 6 >  i; i++) {
            int mesPesquisaFim = mesAtual - i;
            int mesPesquisaInicio = mesPesquisaFim - 1;
            int anoPesquisa = anoAtual;
            if (mesPesquisaInicio == 0) {
                anoPesquisa -= 1;
                mesPesquisaInicio = 12;
            }
            if (mesPesquisaFim == 0) {
                anoPesquisa -= 1;
                mesPesquisaFim = 12;
            }
            String data = mesPesquisaFim + "/" + anoPesquisa;
            int numeroClientes = relatorioCTR.retornarNumeroDeClientesPorMesEAno(mesPesquisaInicio, mesPesquisaFim, anoPesquisa);
            this.modelo_jtl_clienteData.addRow(new Object[]{
                data,
                numeroClientes
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerar;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtl_clientesDate;
    private javax.swing.JTable jtl_clientesFuncionario;
    private javax.swing.JTextField numeroTotalClientes;
    private javax.swing.JTextField numeroTotalFuncionarios;
    // End of variables declaration//GEN-END:variables
}
